<?php
return [
    'enabled' => true,
    'allow_guests' => false,
    'auth_only' => true,
    'require_guest_email' => false,
    'premoderation' => true,
    'autopublish_admin' => true,
    'autopublish_authenticated' => false,
    'max_depth' => 3,
    'per_page' => 20,
    'default_sort' => 'oldest',
    'pagination_mode' => 'pages',
    'enabled_entity_types' => ['article', 'gallery', 'page', 'video', 'news', 'user_profile'],
    'disallow_links' => true,
    'max_url_patterns' => 0,
    'stop_words' => [],
    'min_length' => 8,
    'max_length' => 2000,
    'min_submit_seconds' => 4,
    'delay_between_comments' => 20,
    'comments_per_minute' => 2,
    'comments_per_hour' => 12,
    'honeypot_enabled' => true,
    'time_filter_enabled' => true,
    'spam_action' => 'moderate',
];
